// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  background_image: dynamic(() => import("./BackgroundImage")),
  image_section: dynamic(() => import("./ImageSection")),
  model3_d: dynamic(() => import("./Model3D")),
  section: dynamic(() => import("./Section")),
  sub_title: dynamic(() => import("./SubTitle")),
};
